server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.65.190:1111  #配置nacos地址

management:
  endpoint:
    web:
      exposure:
        include: '*' #默认只公开了/health和/info端点，要想暴露所有端点只需设置成星号
